apiVersion: batch/v1
kind: Job
metadata:
  name: "eval-mlp"
spec:
  backoffLimit: 0

  template:
    spec:
      containers:
      - name: deeplearning-container
        tty: true
        image: docker.io/kunalg106/neuraldeform
        imagePullPolicy: Always
        command: ['bash']
        # args: ['/kunal-data2/NeuralDeformation/code/job_scripts/star_training_p2p.sh']
        # args: ['/kunal-data2/NeuralDeformation/code/job_scripts/star_training_teapose.sh']
        # args: ['/kunal-data2/NeuralDeformation/code/job_scripts/star_training_deform.sh']
        # args: ['/kunal-data2/NeuralDeformation/code/job_scripts/star_training_deform.sh']
        args: ['/kunal-data2/NeuralDeformation/code/job_scripts/evaluate.sh']
        # args: ['kunal-data3/STARDataset/job_scripts/generate.sh']
        lifecycle:
          preStop:
            exec:
              command: ["/viscompfs/user/saibi/stop.sh"]
        resources:
          limits:
            nvidia.com/gpu: 0
            memory: 64Gi
            cpu: 64
            ephemeral-storage: 10Gi
          requests:
            nvidia.com/gpu: 0
            memory: 32Gi
            cpu: 32
            ephemeral-storage: 10Gi
        volumeMounts:
        - name: ssh-secret-volume
          mountPath: "/root/ssh_mount"
        - name: dshm
          mountPath: /dev/shm
        - name: experiments
          mountPath: /experiments
        - name: kunal-data1
          mountPath: /kunal-data1
        - name: kunal-data2
          mountPath: /kunal-data2
        - name: kunal-data3
          mountPath: /kunal-data3

      nodeSelector:
          #  kubernetes.io/hostname: k8s-haosu-22.sdsc.optiputer.net
      tolerations:
        - key: "nautilus.io/haosu"
          operator: "Exists"
          effect: "NoSchedule"

      restartPolicy: Never
      volumes:
        - name: ssh-secret-volume
          secret:

        - name: dshm
          emptyDir:
            medium: Memory

        - name: kunal-data1
          persistentVolumeClaim:
            claimName: kunal-data1

        - name: kunal-data2
          persistentVolumeClaim:
            claimName: kunal-data2

        - name: kunal-data3
          persistentVolumeClaim:
            claimName: kunal-data3

        - name: experiments
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              fsName: nautilusfs
              clusterNamespace: rook
              path: /mc-lab
              mountUser: mc-lab
              mountSecret: ceph-fs-secret

        - name: data
          emptyDir: {}

