kind: Pod
apiVersion: v1
metadata:
  name: kunal
spec:
  affinity:
   nodeAffinity:
     requiredDuringSchedulingIgnoredDuringExecution:
       nodeSelectorTerms:
       - matchExpressions:
         - key: nvidia.com/NVIDIA-A10
           operator: In
           values:
           - NVIDIA-GeForce-GTX-1080-Ti
           - NVIDIA-GeForce-GTX-2080-Ti
           - NVIDIA-RTX-A6000
           - Tesla-V100-SXM2-32GB
           - NVIDIA-TITAN-RTX
           - NVIDIA-RTX-A5000
           - Quadro-RTX-6000
           - Quadro-RTX-8000
           - NVIDIA-A100-PCIE-40GB-MIG-1g.20gb
           - NVIDIA-GeForce-RTX-3090
           - NVIDIA-A10
           
  containers:
  - name: deeplearning-container
    tty: true
    image:  kunalg106/sceneprog:cuda
    imagePullPolicy: Always

    command: ['sleep']
    args: ['infinity']
    lifecycle:
      preStop:
        exec:
          command: ["/hooks/stop.sh"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 32Gi
        cpu: 8
        ephemeral-storage: 50Gi
      requests:
        nvidia.com/gpu: 1
        memory: 16Gi
        cpu: 4
        ephemeral-storage: 50Gi

    volumeMounts:

    - name: kunal-data
      mountPath: /kunal-data
  # nodeSelector:
          #  kubernetes.io/hostname: k8s-haosu-22.sdsc.optiputer.net
  tolerations:
        - key: "nautilus.io/haosu"
          operator: "Exists"
          effect: "NoSchedule"

  restartPolicy: Never
  volumes:
    - name: ssh-secret-volume

    - name: kunal-data
      persistentVolumeClaim:
        claimName: kunal-data


