apiVersion: v1
kind: Pod
metadata:
  name: kunal
spec:
  containers:        
  - name: deeplearning-container
    tty: true
    image: kunalg106/sceneprog:cuda
    imagePullPolicy: Always
    command: ['sleep']
    args: ['infinity']
    lifecycle:
      preStop:
        exec:
          command: ["/hooks/stop.sh"]
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 16Gi
        cpu: 8
        ephemeral-storage: 50Gi
      requests:
        nvidia.com/gpu: 1
        memory: 8Gi
        cpu: 4
        ephemeral-storage: 50Gi
    volumeMounts:
    - name: kunal-data
      mountPath: /kunal-data
  tolerations:
    - key: "nautilus.io/haosu"
      operator: "Exists"
      effect: "NoSchedule"
  restartPolicy: Never
  volumes:
    - name: ssh-secret-volume
    - name: kunal-data
      persistentVolumeClaim:
        claimName: kunal-data


# # apiVersion: v1
# # kind: Pod
# # metadata:
# #   name: gpu-pod-example
# # spec:
# #   containers:
# #   - name: gpu-container
# #     image: tensorflow/tensorflow:latest-gpu
# #     command: ["sleep", "infinity"]
# #     resources:
# #       limits:
# #         nvidia.com/a100: 1
# #       requests:
# #         nvidia.com/a100: 1

# apiVersion: v1
# kind: Pod
# metadata:
#   name: kunal
# spec:
#   containers:
#   - name: gpu-container
#     image: tensorflow/tensorflow:latest-gpu
#     command: ["sleep", "infinity"]
#     resources:
#       limits:
#         nvidia.com/rtx8000: 1
#       requests:
#         nvidia.com/rtx8000: 1
        
#   containers:
#   - name: deeplearning-container
#     tty: true
#     image:  kunalg106/sceneprog:cuda
#     imagePullPolicy: Always

#     command: ['sleep']
#     args: ['infinity']
#     lifecycle:
#       preStop:
#         exec:
#           command: ["/hooks/stop.sh"]
#     resources:
#       limits:
#         nvidia.com/gpu: 1
#         memory: 32Gi
#         cpu: 8
#         ephemeral-storage: 50Gi
#       requests:
#         nvidia.com/gpu: 1
#         memory: 16Gi
#         cpu: 4
#         ephemeral-storage: 50Gi

#     volumeMounts:

#     - name: kunal-data
#       mountPath: /kunal-data
#   # nodeSelector:
#           #  kubernetes.io/hostname: k8s-haosu-22.sdsc.optiputer.net
#   tolerations:
#         - key: "nautilus.io/haosu"
#           operator: "Exists"
#           effect: "NoSchedule"

#   restartPolicy: Never
#   volumes:
#     - name: ssh-secret-volume

#     - name: kunal-data
#       persistentVolumeClaim:
#         claimName: kunal-data



  
